;XLNT II START-UP
;LOADS ALL INCLUDE FILES IN THE CORRECT ORDER

Include "XLnt\XVAR.BB"
Include "XLnt\XWIN.BB"
Include "XLnt\XGAD.BB"
Include "XLnt\XIO.BB"
Include "XLnt\XGFX.BB"
Include "XLnt\XLIST.BB"
Include "XLnt\XCORE.BB"
Include "XLnt\XMENU.BB"
Include "XLnt\XUSER.BB"
Include "XLnt\XPANEL.BB"
Include "XLnt\XPLUGIN.BB"

;IF YOU ARE NOT USING BLITZ 3D (OR DO NOT NEED 3D GADGETS) THEN PLEASE COMMENT-OUT THE
;FOLLOWING LINE->

Include "XLnt\X3D.BB"